name: Security Scan

on:
  push:
    branches:
      - main

permissions:
  contents: write
      
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
  
      - name: Run Docker container
        run: docker run -d --publish 5000:5000 frolvlad/flask-restplus-server-example

      - name: Owasp ZAP (DAST)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:5000'
