name: Security Scan

on:
  push:
    branches:
      - main

permissions:
  contents: write
      
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
  
      - name: Run Docker container
        run: docker run -d --publish 5000:5000 frolvlad/flask-restplus-server-example

      - name: Run Nuclei (DAST)
        run: docker run projectdiscovery/nuclei:latest -target localhost:5000 -j > dast-results.json
        
      - name: Run Bandit (SAST)
        run: bandit -r . -f json -o sast-results.json
