name: Security Scan

on:
  push:
    branches:
      - main

permissions:
  contents: write
      
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install bandit

      - name: Run Nuclei (DAST)
        run: docker run projectdiscovery/nuclei:latest -target localhost:5000
        
      - name: Run Bandit (SAST)
        run: bandit -r .
