name: Security Scan

on:
  push
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      # - name: App Threat(SAST)
      #   uses: AppThreat/sast-scan-action@master
      #   with:
      #     type: "python"
          
      # - name: Upload App Threat(SAST)  
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: SAST_Report
      #     path: reports

      - name: Config docker
        uses: docker/setup-buildx-action@v1

      - name: Run api server
        run: docker run -d --publish 5000:5000 frolvlad/flask-restplus-server-example
      
      - name: Owasp ZAP (DAST)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://127.0.0.1:5000'

      - name: Run Bandit
        uses: banditorg/bandit-action@v1
        with:
          args: --quiet --format=json --output=./bandit-report.json
